# Base image for development
FROM node:22-bullseye-slim AS dev

# Declaring env
ENV NODE_ENV development

# Specify working directory other than /
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Start the development server
CMD ["npm", "start"]
